### ISSUE TITLE
Cambiando exec por file_get_contents

### ISSUE THREAD

**Issue by bobbylechuga** [clsource/guia-webpay#5]
Saludos. Estoy modificando el xt_compra.php para que funcione con file_get_contents. Hago lo que me dicen, defino una contraseña en el archivo previamente creado chkmac.cgi, y no me funciona. 

####### 
$conf{'passwd'} = 'pass123456';
$conf{'log_path'} = 'log/';
#######

file_get_contents("http://localhost/web/cgi-bin/chkmac.cgi?passwd=pass123456&filename=$filename")

¿Esa contraseña exactamente para qué es? ¿lo estoy haciendo mal? 

Gracias!

**Comment by clsource** [comment]
Hola, esos son los archivos de transbank a modo de ejemplo.
no los recomiendo usar para producción.

recomendaría usar mi plugin para prestashop como base
https://github.com/clsource/prestashop-webpay

sobre usar file_get_contents algunos hosting bloquean esa función igualmente.
recomendaría usar curl

http://php.net/manual/es/book.curl.php

Sobre ese archivo "chkmac.cgi" es un script escrito en perl
que hace como puente entre los cgi de transbank y php para evitar el uso de exec.
La contraseña es nada mas para no ser ejecutado por personas ajenas.

Puedes usar cualquier lenguaje que el servidor permita como python o ruby en vez de perl para crear el script.

**Comment by bobbylechuga** [comment]
Gracias por responder. Voy a probar el plugin inmediatamente.

**Comment by bobbylechuga** [comment]
Amigo, me funcionó perfecto en mi local, maravillosamente rápido y bien, ahora, una consulta antes de ponerlo en el servidor del cliente... ¿Los php no utilizan exec, verdad? (es el problema que me da!)

Muchas gracias!

**Comment by clsource** [comment]
si el plugin de prestashop usa exec. 
un servidor que no bloquea exec son los de https://www.silverhost.cl/

**Comment by bobbylechuga** [comment]
Voy a revisar. Quizá la única solución es cambiar a un hosting que sí permita el EXEC. Saludos. Gracias por todo. Voy a tratar de hacer un video con la instalación y configuración del plugin para que la agregues al git del proyecto. Muy buen producto.

**Comment by clsource** [comment]
Gracias.
Onda también es posible adaptar el plugin para que no depende de exec :).
cualquier cosa lo puedes comentar, mucho éxito en todo :+1:
